# Generated by Django 5.1.6 on 2025-02-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_urls_coin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='description',
            field=models.TextField(default='Error 404'),
        ),
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.ImageField(default='Error 404', upload_to=''),
        ),
        migrations.AddField(
            model_name='coin',
            name='name',
            field=models.CharField(default='Error 404', max_length=120),
        ),
        migrations.AlterField(
            model_name='coin',
            name='url',
            field=models.URLField(default='Error 404'),
        ),
    ]
