# Generated by Django 5.1.6 on 2025-02-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_coin_description_coin_image_coin_name_alter_coin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.ImageField(default='Error 404', upload_to='images/'),
        ),
    ]
